version: "2"
services:
  mongodb:
    image: mongo:3.4.7
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    container_name: mongodb

  # This container is used to insert a document.
  mongo_seed:
    build: ./mongo-seed
    image: 283796265/mongo_seed
    depends_on:
      - mongodb
    links:
      - mongodb
    container_name: mongo_seed

  findbeans:
    build: .
    depends_on:
      - mongodb
    links:
      - mongodb
    image: 283796265/findbeans
    ports:
      - "8080:8080"
    container_name: findbeans